% Accelerated Bio-Savart Law to calculate the magnetic field
% (Modified from the original code provided by Zhihua Ren)
% author: Haotian Hong
% update: 6 june 2024
% Location: ShanghaiTech University

%% input
% X,Y,Z: the 3D grid points where the magnetic field is calculated
% coil_trace: the trace of all 15 coil
% currents: the current direction and amplitude parfor the coil array

%% output
% BZ: the magnetic field Bz generated by all current loops

function BZ = cal_Bz_Biotsavart_HHT(X,Y,Z,currents,coils)

num_coils = length(currents);
BZ = zeros(size(X,1), num_coils);

% for i = 1:num_coils
parfor i=1:num_coils
    
    current = currents(i);
    coil_trace = coils{i};
    
    BZ(:,i) = Bz_Biotsavart(X,Y,Z,current,coil_trace);
    
end
BZ = BZ*1e6; % convert to uT
end

function Bz = Bz_Biotsavart(X,Y,Z,current,coil_trace)
mu0=4*pi*1e-7;
x_P = coil_trace(1,:);
y_P = coil_trace(2,:);
z_P = coil_trace(3,:);
Bz = zeros(size(X,1),1);
parfor m=1:size(X,1)
    x_M = X(m);
    y_M = Y(m);
    z_M = Z(m);
    PkM3 = (sqrt((x_M-x_P).^2 + (y_M-y_P).^2 + (z_M-z_P).^2)).^3;
    DBz = ((x_P(2:end)-x_P(1:end-1)).*(y_M-y_P(1:end-1))-(y_P(2:end)-y_P(1:end-1)).*(x_M-x_P(1:end-1)))./PkM3(1:end-1);
    Bz(m) = mu0*current/4/pi*sum(DBz);
end
end